# Generated by Django 3.0.3 on 2020-03-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=64, verbose_name='公司名称')),
                ('company_summary', models.TextField(verbose_name='公司简介')),
                ('company_phone', models.CharField(max_length=15, verbose_name='联系电话')),
                ('company_linkman', models.CharField(max_length=10, verbose_name='联系人')),
                ('company_city', models.CharField(max_length=10, verbose_name='市')),
                ('company_region', models.CharField(max_length=10, verbose_name='区')),
                ('company_address', models.CharField(max_length=10, verbose_name='详情地址')),
                ('recruit_type', models.CharField(max_length=10, verbose_name='工种')),
                ('recruit_num', models.CharField(max_length=10, verbose_name='人数')),
                ('recruit_length', models.CharField(max_length=10, verbose_name='要求工龄')),
                ('recruit_other', models.CharField(blank=True, max_length=64, null=True, verbose_name='其他额外信息')),
            ],
            options={
                'verbose_name': '公司用工信息',
                'verbose_name_plural': '公司用工信息',
            },
        ),
        migrations.CreateModel(
            name='WorkerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('phone', models.CharField(max_length=15, verbose_name='手机')),
                ('city', models.CharField(max_length=10, verbose_name='市')),
                ('region', models.CharField(max_length=10, verbose_name='区')),
                ('address', models.CharField(max_length=64, verbose_name='详情地址')),
                ('gender', models.CharField(max_length=2, verbose_name='性别')),
                ('age', models.PositiveIntegerField(default=1, verbose_name='年龄')),
                ('work_length', models.CharField(max_length=5, verbose_name='工龄')),
                ('work_type', models.CharField(max_length=10, verbose_name='工种')),
                ('work_other', models.CharField(blank=True, max_length=64, null=True, verbose_name='其他额外信息')),
            ],
            options={
                'verbose_name': '工人个人信息',
                'verbose_name_plural': '工人个人信息',
            },
        ),
    ]
